### ISSUE TITLE
Doesn't work on input

### ISSUE THREAD

**Issue by matejlatin** [customd/jquery-number#121]
Been playing around with this plugin and I managed to get it work on elements like span but I can't get it to work on an input. 

I tried `$('input.number').number( true, 2 );` but it just doesn't work. Everything works, just the bit that I really need not :( Is there something obvious that I'm missing?

**Comment by RichardDavies** [comment]
Are you trying it on a HTML5 input type="number"? It only works on "text" inputs per issue #88

**Comment by samatcd** [comment]
This appears to be due to the `input type="number"` limitation. Short of using a shadow input, there's nothing that can be done about this.
