### ISSUE TITLE
Possibility to enter prefix/suffix

### ISSUE THREAD

**Issue by eximius313** [customd/jquery-number#135]
It would be great if jquery-number could handle prefix/suffix values:
```number( 5020.2364, 1, ',', ' ', '%' );``` could output: ```5 020,2 %```
of course % is not editable/deletable just like floating point separator

**Comment by samatcd** [comment]
For this kind of display value, you can just use a `:before` or `:after` pseudo element with `content: '%'` etc. No need for extra code in the plugin to do this.
