### ISSUE TITLE
Negative numbers not supported

### ISSUE THREAD

**Issue by deanputney** [customd/jquery-number#20]
In at least the selector-based formatting, negative numbers are replaced with their absolute value. This is easily corrected for my purposes by adding - to the regex on [line 142 of jquery.number.js](https://github.com/teamdf/jquery-number/blob/master/jquery.number.js#L142).

I haven't submitted a pull request because I'm not really familiar with the rest of the functionality here, but I wanted to bring this issue to your attention. Thanks!

**Comment by PedramFadaei** [comment]
Please change this plugin source by your self, i'm doing this and solved may solution:

1- Find this comment : '//Negative sign' or on this line number 262
2- Change 'setSelectionRange.apply(this, [2,2]);' on line number 271 to this :

if(decimals)
{
    setSelectionRange.apply(this, [2,2]);
}
else
{
    setSelectionRange.apply(this, [2,3]);
}
