### ISSUE TITLE
$('a').val() behaviour, enters 0

### ISSUE THREAD

**Issue by baltena** [customd/jquery-number#27]
If you use .val() to clear the value in an inputfield where .number is applied to, the plugin automatically enters a 0 in the field.
Any way this can be disabled?

In this fiddle: http://jsfiddle.net/4yjnj/3/ you can see what I mean.

**Comment by odumitriu** [comment]
... same problem in v.2.1.5

On line 745, I've added :  if (number === ''){ return '';}
******************
	.replace(new RegExp('[^0-9+\-Ee.]','g'),'');
if (number === ''){ return '';} //<--------------
var n = !isFinite(+number) ? 0 : +number,
******************
