### ISSUE TITLE
Error in number formatting with decimal separator ","

### ISSUE THREAD

**Issue by maurizioavilia** [customd/jquery-number#43]
When:
I apply an AS-U-TYPE on a input type=text valorized _YET_ (es. 10.200)

What I do:
$('.number').number( true, 3, ',', '.' ); 
Notice: 
decimal symbol, a comma
thousan symbol, a full stop

What I get:
An input type valorized with string: 10.200,000
The value of element is (accessing by .val) 10200

This behavior is in disagreement with I think it must be.
I'm expected an input type valorized with: 10,200

And this is the comportamet I find if:
- apply the function $('.number').number( true, 3, ',', '.' ); on an EMPTY text
- write on it with .val('10.200')
- I get an input type valorized with 10,200
- The value (with val funcion) is 10.200

Thanks

**Comment by mauricioDarriens** [comment]
In the latest version (2.16), the bug reappears
