### ISSUE TITLE
Length of input, stuck of 18 chars

### ISSUE THREAD

**Issue by newinstance** [customd/jquery-number#75]
Hi, I use the plugin to format currency and other, but in one case I need to allow only numbers on the input, no decimals, no currency formats, just allow numbers in the field. The problems is that the length is like 18 chars, and then it starts rounding the last character.

**Comment by samatcd** [comment]
If you only need numbers, no decimals and no formatting, then you're best to just use an `<input type="number" />` field, and don't apply the plugin at all.

**Comment by newinstance** [comment]
Although it has been a lot of time since your answer I want to say thanks. Sometimes we get blind in the process, thank you.
