### ISSUE TITLE
Missing jquery.number.min.js.map

### ISSUE THREAD

**Issue by Jako** [customd/jquery-number#80]
sourceMappingURL=jquery.number.min.js.map is referenced in jquery.number.min.js

**Comment by luebbert42** [comment]
+1 :-)

**Comment by danlo** [comment]
+1

**Comment by samatcd** [comment]
Ok, no problem. I'll get this sorted for the next release.

**Comment by ArsenBespalov** [comment]
@samatcd And where is map file?

**Comment by samatcd** [comment]
There hasn't been a new release yet. You're welcome to do this and submit a PR if you need it urgently.

**Comment by ArsenBespalov** [comment]
@samatcd Ok! I create map file and pull request.

**Comment by samatcd** [comment]
Thanks, Merged :-)
