### ISSUE TITLE
Canot add "-" (minus) in front when modifying the value

### ISSUE THREAD

**Issue by vasilp** [customd/jquery-number#89]
**Steps to reproduce:**
1. Enter some value greater than 0, for example "123".
2. Go to the beginning of the input and press "-" (minus)

Expected is to add "-" in front and the value to become "-123".
Realized result is: the modification is prevented, so value stays untouched.

**Notes:**
Adding "-" for negative values works only if there is no content in the input, only if the user starts typing can enter negative values. Otherwise, the value should be removed and entered again, preceded with "-" before that, which is very uncomfortable when working with large numbers and can cause user errors. A lot of users will actually prefer just inserting "-" in from rather than typing everything again with negative sign.

**Comment by vasilp** [comment]
Actually the issue was in an old version. The current version work properly with '-' symbol.

**Comment by samatcd** [comment]
Great, thanks for that.
